name: Build/release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn install

      - name: Make files
        run: yarn make

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows
          path: out
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "out/make/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}